-- Desafio lançado pelo mago

BEGIN
  FOR T
    IN (SELECT X.SEQPROMOCESPECIAL FROM consinco.MRL_PROMOCESPECIALHIST X
        WHERE X.STATUS = 'P' AND DTAFIM < TRUNC(SYSDATE))
    LOOP 
  UPDATE consinco.MRL_PROMOCESPECIALHIST Y
  SET Y.STATUS = 'I'
  WHERE Y.SEQPROMOCESPECIAL = T.SEQPROMOCESPECIAL;
  END LOOP;
  COMMIT;
  END;
