BEGIN
  FOR T 
 IN (SELECT X.SEQFORNECEDOR, X.PZOPAGAMENTO, Y.UF
         FROM CONSINCO.MAF_FORNECDIVISAO X
         INNER JOIN CONSINCO.GE_PESSOA Y
         ON Y.SEQPESSOA = X.SEQFORNECEDOR
         AND Y.UF = 'EX'
         AND X.PZOPAGAMENTO != '365')
LOOP
UPDATE MAF_FORNECDIVISAO X
SET X.PZOPAGAMENTO = 365
WHERE X.SEQFORNECEDOR = T.SEQFORNECEDOR;
END LOOP;
END;
